use_frameworks!

target 'DS_Example' do
  pod 'DS', :path => '../'

  target 'DS_Tests' do
    inherit! :search_paths

		pod 'DS', :path => '../'
    pod 'Specta'
		pod 'Expecta'
		pod 'FBSnapshotTestCase'
		pod 'Expecta+Snapshots'
  end
end
